server:
  port: 8080

spring:
  # Database configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 10000 #10s
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - https://www.googleapis.com/auth/userinfo.profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

        google:
          auth:
            endpoint: https://accounts.google.com/o/oauth2/v2/auth

  # liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
    contexts: ${spring.profiles.active}

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # Email Configuration (with Gmail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: pdanhkhoaa@gmail.com
    password: hpnr kxtf dzit lovg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jobhunter:
  jwt:
    base64-secret: ${JWT_SECRET_KEY}
    access-token-validity-in-seconds: 8640000  # 100 days
    refresh-token-validity-in-seconds: 8640000  # 100 days

  # File upload base path
  upload-file:
    base-uri: ${MY_UPLOADFILE_STORAGE}

#enable swagger
springdoc:
  override-with-generic-response: false
