spring:
  application:
    name: jobhunter
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  # Pagination Configuration
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  config: classpath:config/log4j2/log4j2-${spring.profiles.active}.xml


