spring:
  application:
    name:jobhunter-BE

#  database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/jobhunter
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jobhunter:
# JWT Configuration
  jwt:
    base64-secret: TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
    access-token-validity-in-seconds: 8640000  # 100 days
    refresh-token-validity-in-seconds: 8640000  # 100 days

# File upload base path
  upload-file:
    base-uri: file:///S:/Java/JavaSP/job%20hunter/upload/